openapi: 3.0.0
info:
  title: Sample Ktor API
  version: 1.0.0
  description: A sample API built with Ktor.
paths:
  /:
    get:
      summary: Get a hello world message
      responses:
        '200':
          description: A simple hello world message
  /login:
    post:
      summary: Login a user and get a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: A JWT token
  /users:
    get:
      summary: Get a list of all users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of users
    post:
      summary: Create a new user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: The created user

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        age:
          type: integer
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
